language: python
python:
  - 3.8
  - 3.7
  - 3.6
install:
  - pip install -r requirements/install.txt
  - pip install -r requirements/test.txt
  - pip install coveralls
script:
  - coverage run --source=crony setup.py test
after_success:
  - coveralls
